PBM=ch.supsi.imageEditor.backend.business.images.export.ExportToPgmStrategy
PGM=ch.supsi.imageEditor.backend.business.images.export.ExportToPpmStrategy
PPM=ch.supsi.imageEditor.backend.business.images.export.ExportToPpmStrategy