rotate-90-right=ch.supsi.imageEditor.backend.business.operation.allOperations.Rotate90DegreesRight
rotate-90-left=ch.supsi.imageEditor.backend.business.operation.allOperations.Rotate90DegreesLeft
flip-side-to-side=ch.supsi.imageEditor.backend.business.operation.allOperations.FlipSideToSide
flip-upside-down=ch.supsi.imageEditor.backend.business.operation.allOperations.FlipUpsideDown
negative=ch.supsi.imageEditor.backend.business.operation.allOperations.InvertColor