rotate-90-right=Operations.rotate-90-right
rotate-90-left=Operations.rotate-90-left
flip-side-to-side=Operations.flip-side-to-side
flip-upside-down=Operations.flip-upside-down
negative=Operations.negative