rotate-90-right=Operations.rotate-90-right
rotate-90-left=Operations.rotate-90-left
flip-side-to-side=Operations.flip-side-to-side
flip-up-side-down=Operations.flip-up-side-down
negative=Operations.negative